/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mxu_app_kkplayer_interop_IGraphBuilder */

#ifndef _Included_com_mxu_app_kkplayer_interop_IGraphBuilder
#define _Included_com_mxu_app_kkplayer_interop_IGraphBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mxu_app_kkplayer_interop_IGraphBuilder
 * Method:    openFile
 * Signature: (Ljava/lang/String;)Lcom/mxu/app/kkplayer/interop/IMediaControl;
 */
JNIEXPORT jobject JNICALL Java_com_mxu_app_kkplayer_interop_IGraphBuilder_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mxu_app_kkplayer_interop_IGraphBuilder
 * Method:    closeFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mxu_app_kkplayer_interop_IGraphBuilder_closeFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
