/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mxu_app_kkplayer_interop_IMediaControl */

#ifndef _Included_com_mxu_app_kkplayer_interop_IMediaControl
#define _Included_com_mxu_app_kkplayer_interop_IMediaControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mxu_app_kkplayer_interop_IMediaControl
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mxu_app_kkplayer_interop_IMediaControl_start
  (JNIEnv *, jobject);

/*
 * Class:     com_mxu_app_kkplayer_interop_IMediaControl
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mxu_app_kkplayer_interop_IMediaControl_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_mxu_app_kkplayer_interop_IMediaControl
 * Method:    pause
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mxu_app_kkplayer_interop_IMediaControl_pause
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
